version: "3.8"
services:
  api:
    container_name: event-manager-api
    build: .
    image: event-manager-api
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: event-manager-postgres
    image: postgres
    restart: always
    ports:
      - '5778:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=event-manager