version: "3.8"
services:
  api-test:
    container_name: event-manager-api-test
    build: .
    image: event-manager-api
    ports:
      - "4001:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - DATABASE_URL=postgresql://admin:password@event-manager-postgres-test:5432/event-manager?schema=public
    command: npm run test:watch
    depends_on:
      - postgres-test

  postgres-test:
    container_name: event-manager-postgres-test
    image: postgres
    restart: always
    ports:
      - '5779:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=event-manager